spring:
  datasource:
    url: jdbc:sqlite:soilops.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: com.tietoevry.soilops.config.SQLiteDialect
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: on

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: c03213601d7f62d0d382
            client-secret:
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
          google:
            client-id: 41362502913-agvvbfifu45f5om68do15n16nhr0dje3.apps.googleusercontent.com
            client-secret: 
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
              -
app:
  security:
    tokenSecret: MySecretToken
    tokenTimeToLive: 864000000
    tokenShortTimeToLive: 60000
